### ISSUE TITLE
"vagrant ssh" failed on cygwin(win7)

### ISSUE THREAD

**Issue by turutosiya** [mitchellh/vagrant-aws#122]
I'm trying to use vagrant-aws onmy cygwin (win 7), but failed on ssh connection.
here is what I got with VAGRANT_LOG=debug

>  INFO subprocess: Starting process: ["E:\cygwin\root\bin/ssh.EXE"]
> DEBUG subprocess: Selecting on IO
> DEBUG subprocess: stderr: usage: ssh [-1246AaCfgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
>            [-D [bind_address:]port] [-e escape_char] [-F configfile]
>            [-I pkcs11] [-i identity_file]
>            [-L [bind_address:]port:host:hostport]
>            [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
>            [-R [bind_address:]port:host:hostport] [-S ctl_path]
>            [-W host:port] [-w local_tun[:remote_tun]]
>            [user@]hostname [command]
> DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
> DEBUG subprocess: Exit status: 255
>  INFO ssh: Invoking SSH: ["{dns name of the instance}", "-p", "22", "-o", "DSAAuthentication=yes", "-o", "LogLevel=FATAL", "-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null", "-o", "IdentitiesOnly=yes", "-i", "{pem file path}"]

**Comment by dysinger** [comment]
Related to #382?

**Comment by andrewkew-aft** [comment]
@turutosiya - make sure that in your Vagrant file you have the following config set

     override.ssh.private_key_path = "/absolulte/path/to/pem"

In the ssh_config/config.erb for vagrant it uses this value to set the ssh switch IdentityFile to this value. 

    <% private_key_path.each do |path| %>
    <% if path.include?(" ") -%>
      IdentityFile "<%= path %>"
    <% else -%>
      IdentityFile <%= path %>
    <% end -%>
    <% end -%>

When using ssh if the switch IdentitiesOnly = yes (which is does) then IdentityFile has to be set as the default value for IdentityFile wont match your AWS key.

From the ssh_config(5) man page: http://unixhelp.ed.ac.uk/CGI/man-cgi?ssh_config+5 

     IdentitiesOnly
	     Specifies that ssh should only use the authentication identity
	     files configured in the ssh_config files, even if the ssh-agent
	     offers more identities.  ....

     IdentityFile
	     Specifies a file from which the user's RSA or DSA authentication
	     identity is read.	The default is ~/.ssh/identity for protocol
	     version 1, and ~/.ssh/id_rsa and ~/.ssh/id_dsa for protocol ver-
	     sion 2.  
             .....

Try setting the private key path in your Vagrant file and see if that works.
