### ISSUE TITLE
allow for custom ssh port

### ISSUE THREAD

**Issue by ericsmalling** [mitchellh/vagrant-aws#126]
It would be very nice to be able to configure a custom ssh port for aws instances.  Not being much of a Ruby developer, I'm fumbling trying to implement it though!

**Comment by seglo** [comment]
If I do the iptables trick.  Or I have an AMI that's not configured to use the standard SSH port, how do I configure vagrant-aws to connect to a different port?

**Comment by ericsmalling** [comment]
The point of the issue was that I was unable to use vagrant-aws with custom ssh ports.   My iptables trick was what I was using w/out Vagrant.  Unfortunately, I've changed jobs since then and haven't had a need to use this since 2013; brain fog has set in about where we left off on this, sorry. :(

**Comment by seglo** [comment]
@ericsmalling No problem, I totally understand!

In regards to this issue, I also understand that you wouldn't want to incorporate platform-specific code to do something like change the SSHD port, but I think it's reasonable to provide a way to have vagrant-aws use a non-standard SSHD port if an AMI is already provisioned that way.  Perhaps someone else can pipe in if that's reasonable, or if it's already possible and I'm missing something.

Also, just to add a little more insight to this ticket, this is the `user_data` I used to add a **persistent** port forward to my CentOS 7 AMI for a non-standard port (forwards 2222 to 22).

```
aws.user_data = "#!/bin/bash\niptables -t nat -A PREROUTING -p tcp --dport 2222 -j DNAT --to-destination :22\niptables-save | tee /etc/iptables.conf\necho \"iptables-restore < /etc/iptables.conf\" | tee --append /sbin/ifup-local\nchmod u+x /sbin/ifup-local\n"
```

**Comment by lelandlater** [comment]
Can I use `aws.user_data` to change the SSH port before Vagrant attempts SSH?

**user_data.txt**
```
#!/bin/bash -ex
perl -pi -e 's/^#?Port 22$/Port 998/' /etc/ssh/sshd_config
service sshd restart || service ssh restart
``` 

**Vagrantfile**
```
require 'vagrant-aws'

Vagrant.configure('2') do |config|

  config.vm.box = 'aws-dummy'

  config.vm.provider 'aws' do |aws,override|
  # Read AWS authentication from the environment
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']

    aws.keypair_name = 'key'

    aws.region = 'us-east-1'
    aws.ami = 'ami-id'
    aws.instance_type = 't2.small'

    aws.security_groups = ['group-id1', 'group-id2']
    aws.subnet_id = 'subnet-id'

    aws.user_data = File.read("user_data.txt")

    override.ssh.username = 'ubuntu'
    override.ssh.private_key_path = 'key-path'
    override.ssh.port = 998
  end
end
```

The `override.ssh.port` was not working as I expected. Are there any other settings to change?

**Comment by ericsmalling** [comment]
Ancient history - closing
