### ISSUE TITLE
Rsync exclusion option conflicts with Vagrant's

### ISSUE THREAD

**Issue by rossmeissl** [mitchellh/vagrant-aws#232]
#156 allows the user to exclude files from AWS's synced folders implementation (which uses rsync). As far as I can tell this:

1. is undocumented and
2. conflicts with Vagrant's [`rsync__exclude`](http://docs.vagrantup.com/v2/synced-folders/rsync.html) option ("excludes" vs. "exclude" and single versus double underscore).

Could @mitchellh or @tralamazza please clarify if this is intentional?

**Comment by ColinHebert** [comment]
This issue should be closed.
