### ISSUE TITLE
Sits at "Waiting for SSH to become available..." indefinitely 

### ISSUE THREAD

**Issue by while1eq1** [mitchellh/vagrant-aws#259]
Vagrant 1.6.3
vagrant-aws (0.5.0)

when I run a vagrant up --provider=aws it will launch the instance on aws sucessfully. Im even able to ssh in from another terminal. But from the terminal I launched "vagrant up --provider=aws" from it just sits at "Waiting for SSH to become available..." indefinitely.

Vagrantfile:

``` ruby
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "dummy"

  config.vm.provider :aws do |aws|
    aws.access_key_id = 'my_key_id'
    aws.secret_access_key = 'my_secret_key'
    aws.keypair_name = 'name'

    aws.ami = 'ami-fb8e9292'

    aws.instance_type = 'm1.small'
    aws.region = 'us-east-1'
    aws.tags = {:env => 'my-env'}
  end
```

**Comment by kenorb** [comment]
This is by design, you need to add the existing `aws.keypair_name` in order to log-in, otherwise you won't be able to SSH into it.
