### ISSUE TITLE
Feature: Ability to tag created volumes

### ISSUE THREAD

**Issue by hamiltont** [mitchellh/vagrant-aws#284]
Unless I've missed this somewhere, it would be a welcome addition. Would likely require a second request to aws

**Comment by skalenji** [comment]
aws.tags is only tagging the instance but not the volumes. In fact I think it's impossible to tag the volumes within the same call. Most likely it will need to pull all volumes and apply the same tags to each one separately

**Comment by jhoblitt** [comment]
It used to be that tagging required a separate call but it is now possible to tag volumes as part of the instance run call.

https://aws.amazon.com/blogs/aws/new-tag-ec2-instances-ebs-volumes-on-creation/

**Comment by pruteanu** [comment]
Is this feature working for you? My tags are not propagated from the ec2 instance to the ebs volume. 

Indeed, @jhoblitt is right, AWS added this feature, but this does not seem to be reflected in this library. Or maybe i'm doing it wrong. Trying complicated workarounds with metadata.
