### ISSUE TITLE
Unable to install plugin on 1.6.3

### ISSUE THREAD

**Issue by maheshchandwani** [mitchellh/vagrant-aws#286]
C:\APS>vagrant plugin install vagrant-aws  --verbose
Installing the 'vagrant-aws' plugin. This can take a few minutes...
Fetching source index from http://gems.hashicorp.com/
Retrying source fetch due to error (2/3): Bundler::HTTPError Could not fetch spe
cs from http://gems.hashicorp.com/
Retrying source fetch due to error (3/3): Bundler::HTTPError Could not fetch spe
cs from http://gems.hashicorp.com/
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Could not fetch specs from http://gems.hashicorp.com/
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Could not fetch specs from http://gems.hashicorp.com/

C:\APS>
C:\APS>vagrant -v
Vagrant 1.6.3

C:\APS>

**Comment by tacnoman** [comment]
At Windows 10, I installed this first:
vagrant plugin install vagrant-proxyconf

And all plugins was worked like a charm
