### ISSUE TITLE
rsync__exclude not excluding anything at all

### ISSUE THREAD

**Issue by dsantanu** [mitchellh/vagrant-aws#304]
I can sync directories without any issue but if I want to exclude certain file-type(s) it doesn't work at all. I wanted all the  ```.json``` and ```.sh``` files to be excluded, so I have this:

```puppet
config.vm.synced_folder "./scripts", "/var/tmp/"+nodes_cfg['aws_env']+"/scripts", 
                         type: "rsync", rsync__exclude: [ "*.json", "*.sh"]
```
which is syncing ```scripts``` alright but with everything in it, including the file-types in the rsync__exclude list. Did I do anything wrong here or anything am I still missing? Best!

**Comment by cameronraysmith** [comment]
`Vagrant 1.7.2`
`vagrant-aws 0.6.0`

I am experiencing the equivalent of this issue mitchellh/vagrant-aws#304 and mitchellh/vagrant#4248: rsync does not respect excludes. The suggestion in [this comment](https://github.com/mitchellh/vagrant/issues/4248#issuecomment-52071254), that the method implemented in mitchellh/vagrant-aws#156: 
```
config.vm.synced_folder '.', '/vagrant', :rsync_excludes => ['chef/tmp', 'tmp']
```
resolves the issue is also not working for me.

**Comment by ColinHebert** [comment]
This issue should be closed

**Comment by michaek** [comment]
@rtyler I'm not sure this issue should be closed - the last comment says "the method implemented in ... is also not working for me", though some of what I've replaced with an ellipsis makes it harder to parse that meaning.

I'm also not able to successfully exclude files from the rsync, using any of the documented configuration.

**Comment by michaek** [comment]
Currently, I'm working around this with the following:

```
vagrant ssh-config > ssh.config # One time, for the following command
rsync -ravz -e "ssh -F ssh.config" --exclude .vagrant --exclude .git --exclude-from .gitignore --delete ./ default:/vagrant/
```

An upside is that when the delta is small the bare rsync command is many times faster than the rsync command wrapped in Vagrant initialization and abstraction.

**Comment by michaek** [comment]
Actually - the implementation does work. The problem that I was running into, and perhaps the problem of others, is that (as documented) changes to the Vagrantfile require a `vagrant reload` to take effect, and I was expecting those changes to be immediately applied to a `vagrant provision` or a `vagrant rsync` command, and they were not.
