### ISSUE TITLE
uninitialized constant Vagrant::VM on vagrant up

### ISSUE THREAD

**Issue by Quinn-ActiveState** [mitchellh/vagrant-aws#305]
$ vagrant -v
Vagrant 1.6.5

$ vagrant plugin list
vagrant-aws (0.0.1)
vagrant-login (1.0.1, system)
vagrant-share (1.1.2, system)

$ vagrant up
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

uninitialized constant Vagrant::VM

Have uninstalled and reinstalled the vagrant-aws plugin, also vagrant itself. Experience the same issue on vagrant 1.6.4.

**Comment by ColinHebert** [comment]
Should be closed (using newer version of the plugin would fix that).
