### ISSUE TITLE
Creating multi-machine Vagrantfile with AWS?

### ISSUE THREAD

**Issue by martinambrus** [mitchellh/vagrant-aws#348]
Is it possible to set up a multi-machine setup with this plugin?
I tried a simple blocks setup like the ones on [Vagrant's multi-machine docs page](https://docs.vagrantup.com/v2/multi-machine/) but that don't seem to work (and I'm no expert here). For example, this would mix provisioning of the second machine into the first machine for some reason...

    config.vm.provider :aws do |apache1, override|
      ... do stuff ...
      override.vm.provision :shell, :path => "apache1.sh"
    end

    config.vm.provider :aws do |apache2, override|
     ... do stuff ...
     override.vm.provision :shell, :path => "apache2.sh"
    end

Sorry for a question but I couldn't find any other place to ask.

**Comment by martinambrus** [comment]
I've ended up with updating the structure to something like this:

    config.vm.define "apache1" do |config_apache1|
    config_apache1.vm.provider :aws do |apache1, override|
      ... do stuff ...
      override.vm.provision :shell, :path => "apache1.sh"
    end
    end

    config.vm.define "apache2" do |config_apache2|
    config_apache2.vm.provider :aws do |apache2, override|
     ... do stuff ...
     override.vm.provision :shell, :path => "apache2.sh"
    end
    end

... seems to work :)

**Comment by bonzofenix** [comment]
Worked for me too! thanks for sharing!

**Comment by GBmonmon** [comment]
if you put those ec2 in a single Vagrantfile, how are you supposed to use vagrant ssh? How does the program know which ec2 to ssh into?

**Comment by tournageCoding** [comment]
You can run 'vagrant status' to see the names of the VMs. Then run 'vagrant ssh machineName' to SSH to a certain machine
