### ISSUE TITLE
Feature request: parse boto config for AWS keys

### ISSUE THREAD

**Issue by revmischa** [mitchellh/vagrant-aws#351]
We store our AWS API keys in the boto config file (`~/.boto`). It would be really helpful if vagrant could use that if it exists. Should be straightforward with something like [IniParse](https://rubygems.org/gems/iniparse)

**Comment by amosshapira** [comment]
I do something similar for reading ~/.aws/credentials in my Vagrantfile:
```
require 'inifile'
...
  aws_credentials = IniFile.load(File.expand_path('~/.aws/credentials'))
  aws_config = IniFile.load(File.expand_path('~/.aws/config'))
  $aws_access_key_id = aws_credentials['default']['aws_access_key_id']
  $aws_secret_access_key = aws_credentials['default']['aws_secret_access_key']
  $aws_region = aws_config['default']['region']
```
(I use global variables because they are also used elsewhere)

Is this what you are asking for? Then it wouldn't require anything special to be implemented in Vagrant itself.

**Comment by revmischa** [comment]
I would love it if my devs could just put their access keys in one place (boto config) and have them magically work with vagrant.

**Comment by amosshapira** [comment]
@revmischa I'm not sure I follow - can't you do something similar to the sample code I provide?

**Comment by revmischa** [comment]
`~/.aws/credentials` != `~/.boto`

**Comment by amosshapira** [comment]
Yes I know that, what stops you from tweaking a similar code into your Vagrantfile, just like I demostrated above?

Looking at http://boto.readthedocs.org/en/latest/boto_config_tut.html it seems pretty similar if not identical format.

**Comment by revmischa** [comment]
ah yes I see. I swear I had tried doing something similar to what you are suggesting previously. I kept getting issues with the `require IniParse` blowing up in vagrant.
Thanks for getting back to me on this.

**Comment by amos-stan** [comment]
> I kept getting issues with the require IniParse blowing up in vagrant.
I learned that the trick is to install any extra gem just like plugins - `vagrant plugin install inifile` should make it accessible to the Vagrantfile.

Good luck.
