### ISSUE TITLE
Support dedicated Tenancy when create instances at AWS?

### ISSUE THREAD

**Issue by IvanTing** [mitchellh/vagrant-aws#375]
According to this Amazon documentation http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/dedicated-instance.html, AWS users can  launch instances into a VPC with a tenancy attribute ('default' for running on shared hardware and 'dedicated' for running on single-tenant hardware).
Will vagrant-aws provide attribute to set the tenancy when create instances at AWS?

E.g. in the Vagrantfile, 
aws.tenancy=default    (for instance runs on shared hardware)
or
aws.tenancy=dedicated (for instance runs on single-tenant hardware)

**Comment by monsterbear** [comment]
I just supplied #395  that adds this functionality.  Fairly simple since the library the plugin uses, fog, already had support for this feature.
