### ISSUE TITLE
On VPN: vagrant ssh aws does not uses (resolves to) the right IP

### ISSUE THREAD

**Issue by colegatron** [mitchellh/vagrant-aws#396]
Maybe I overlooked something on the doc: There is currently any way to instruct vagrant to use the instance dns name instead the public ip address? 

My non-working scenario:
I have a openvpn server in my vpc's to access remotely via openvpn tunnel.

When launching a instance with vagrant inside the vpc (without assigning EIP), the instance is up and running, but then vagrant tries to connect to the instance though ssh using THE PUBLIC IP (52.17.x.x) and of course it is not able to connect to it because the security groups (it is right).
Vagrant should connect using the DNSNAME of the instance instead of using directly the IP.

I can connect to the instance from the terminal using the dns name. 
This is because the behaviour of AWS dns.
When you try to resolve the public dns name, if you are outside AWS, it resolves to 52.17.x.x, but if you are inside the AWS VPC, it resolves to the internal IP (10.x.x.x).
When you connect to a vpn in aws your (client side) resolv.conf should be updated to use the dns server 172.31.0.2 under linux (under windows and mac clients openvpn does it automatically)

Maybe there is an option in vagrant to configure it should resolve the dns hostname and not the host ip address, but I can't find it anywere in the doc

**Comment by joerwin** [comment]
In the past I have instructed vagrant-aws to utilize the instances internal IP address rather than the external IP address by setting aws.ssh_host_attribute = :private_ip_address as mentioned here: https://github.com/mitchellh/vagrant-aws/issues/294. 

While this will not utilize the AWS DNS server, it will connect on your private network address assuming you are connected to your VPN.

**Comment by colegatron** [comment]
I spend the entire yesterday's morning with this until I thought to ask here.

Thank you very much, that saved my day!
