### ISSUE TITLE
Project Abandoned? Should be provided out of the box with Vagrant?

### ISSUE THREAD

**Issue by ColinHebert** [mitchellh/vagrant-aws#397]
This project hasn't been updated in ages. It seems that there is little to no follow up on the various issues opened over the past few months.

Is the project still alive? Should the support of AWS be a part of the default distribution of Vagrant? Is there someone to maintain the project and release new versions?

cc @mitchellh @rtyler

**Comment by rtyler** [comment]
@ColinHebert not abandoned, at least from my perspective, I've just had a plethora of other things :P

**Comment by ColinHebert** [comment]
I see. But given the number of people using this project, should there be more maintainers looking after it?

Side question, will there be a new release soon~?

**Comment by rtyler** [comment]
@ColinHebert yes and yes :)

It's rather hard to get volunteers to materialize, though there's been some good periodic contributors like yourself. My reticence largely stems from the very poor test suite in place for this plugin :/
