### ISSUE TITLE
Could it be possible to specify the name and/or description of the EC2 box

### ISSUE THREAD

**Issue by danielbryantuk** [mitchellh/vagrant-aws#4]
First off let me say that Vagrant 1.1.0 + vagrant-aws has blown my mind! Thanks for all the hard work, and congrats!

A (really) small issue that I'm having is that I'm not able to identify to others in my team which EC2 boxes are running via Vagrant (we run lots of EC2 instance). I know you can set instance tags via the aws.config within the plugin config, but would it also be possible to add functionality to allow the setting of an EC2 instance name or description please?

This way the team can easily see which boxes are being managed via Vagrant! :)

**Comment by btiernay** [comment]
This actually doesn't work for me. I continue to have to manually edit the instance name in the AWS console:
```ruby
  # Launching
  vms.vm.provider :aws do |aws, override|
    # Authentication
    aws.access_key_id = ENV['AMAZON_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AMAZON_SECRET_ACCESS_KEY']
    
    # Instance (Ubuntu)
    aws.ami = "ami-9eaa1cf6"
    aws.instance_type = a['instance_type']
    
    # Security
    aws.keypair_name = "fstream"
    aws.security_groups = ["default"]
    
    # Metadata
    aws.tags["Name"] = box[:name]
    
    # Vagrant base (required)
    override.vm.box = "dummy"
    override.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
  
    # Access          
    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "~/.ssh/fstream.pem"
  end
```
Am I don't something boneheaded?
