### ISSUE TITLE
Release of a new version

### ISSUE THREAD

**Issue by ColinHebert** [mitchellh/vagrant-aws#413]
Hi @rtyler,

Would it be possible to cut a new version of vagrant-aws?

This version is almost one year old, and there's been a lot of progress since then.

**Comment by davidski** [comment]
Ditto. I'm particularly interested in getting access to the option to enable/disable source/destination checks. This was committed about two months ago.

**Comment by jjn1056** [comment]
++ it would be great to get some sort of statement about maintenance of this project since its all over search results and even in the vagrant main site docs, yet there's clearly a lot of issues which we'd like to clean up.

**Comment by apolloclark** [comment]
+1

**Comment by rtyler** [comment]
0.7.0 has been cut to rubygems.org

**Comment by ColinHebert** [comment]
![It's Happening!](https://i.imgur.com/7drHiqrh.gif)

**Comment by rtyler** [comment]
![excited](http://i.imgur.com/KitxP.gif)
