### ISSUE TITLE
Valid region reported as invalid

### ISSUE THREAD

**Issue by rodush** [mitchellh/vagrant-aws#417]
> /Users/rodush/.vagrant.d/gems/gems/fog-aws-0.7.6/lib/fog/aws.rb:232:in `validate_region!': Unknown region: "eu-west-1a" (ArgumentError)
> **Host OS** _OS X El Capitan 10.11.1_
> **Vagrant** _1.7.4_

**Comment by davidski** [comment]
You're including the AZ with the region. The proper region should be just `eu-west-1`.
