### ISSUE TITLE
Vagrant provision no longer updating chef cookbooks

### ISSUE THREAD

**Issue by 3vcloud** [mitchellh/vagrant-aws#426]
Hi,

As mentioned in https://github.com/mitchellh/vagrant-aws/issues/385 , a previous commit has removed the SyncedFolders method on provision, which has caused some stress.

We use a forked version of this repo using spot instances for our development to save some money. I have a chef script that uses the current server's IP address to assign an A record in route 53 (because load balancing at $0.028ph is too expensive for our development needs)

```
ip_address = open('http://169.254.169.254/latest/meta-data/public-ipv4', options = { proxy: false }, &:gets)

unless node['load_balancer'].nil? || node['load_balancer'].empty?
	aws_elastic_lb node['load_balancer'] do
		aws_access_key aws_access_key_id
		aws_secret_access_key aws_secret_access_key
		name node['load_balancer']
		action :register
	end
end

unless node['route_53_domain'].nil? || node['route_53_domain'].empty?
	node['route_53_domain'].each do |domain,subdomain|
		# Create a zone for example.com
		amazon_dns_zone domain do
			aws_access_key_id     aws_access_key_id
			aws_secret_access_key aws_secret_access_key
		end
		amazon_dns_record subdomain do
			domain domain
			value ip_address
			type "A"
			ttl 60
			aws_access_key_id     aws_access_key_id
			aws_secret_access_key aws_secret_access_key
		end
	end
end
```

This needs to be run on the AWS server to test, but without syncing the changes on provision, and the fact that a spot instance can't be stopped and started again, I'm having to scrap the server every time to test this.

**Comment by 3vcloud** [comment]
P.S. Sorry for lack of message body, slipped on submission!

**Comment by yoshiwaan** [comment]
As you've probably worked out this is a long running issue and actually impacts multiple plug-ins for vagrant, not just AWS.
There's been little movement to get the problem fixed, although it needs to be fixed upstream (something like https://github.com/mitchellh/vagrant/issues/5850).
My suggestion in the meantime (and maybe permanently because it works well) would be to move your test over to Test Kitchen. Test Kitchen + kitchen-ec2 has worked flawless since the last few versions for me.

**Comment by 3vcloud** [comment]
Thanks for the feedback @yoshiwaan . I'm also getting feedback from the team about issues with the AWS machines losing reference to the synced folders altogether - the fix for this normally being to delete synced_folders and re-provision - but would still give a big issue if we had to reload a production server in this scenario.

Either way, definitely looks like a bug with vagrant itself and not this plugin, so I'll close this one off and subscribe to your other issue - thanks again :+1:
