### ISSUE TITLE
Can't SSH???

### ISSUE THREAD

**Issue by iangcarroll** [mitchellh/vagrant-aws#43]
I launched an instance with everything setup correctly. Port 22's open. Any idea?
ian@rtc ~/discourse> vagrant up --provider=aws
Bringing machine 'default' up with 'aws' provider...
[default] Warning! The AWS provider doesn't support any of the Vagrant
high-level network configurations (`config.vm.network`). They
will be silently ignored.
[default] Launching an instance with the following settings...
[default]  -- Type: m1.small
[default]  -- AMI: ami-7747d01e
[default]  -- Region: us-east-1
[default]  -- SSH Port: 22
[default]  -- Keypair: New Macbook Air Keys
[default] Waiting for instance to become "ready"...
[default] Waiting for SSH to become available...
When I Ctrl+C it, it then says it's ready and then kills it. :\

**Comment by alxempirical** [comment]
> Get some VAGRANT_LOG=debug output and gist that. It shouldn't have your credentials in there (verify)

@mitchellh, it turns out it *does* have your credentials.  `VAGRANT_OLD_ENV_AWS_ACCESS_KEY` and `VAGRANT_OLD_ENV_AWS_SECRET_KEY`.
