### ISSUE TITLE
vagrant-aws version mismatch

### ISSUE THREAD

**Issue by schasse** [mitchellh/vagrant-aws#437]
Hi there,

I recognized that the gem's version is `0.7.0` but in [`lib/vagrant-aws/version.r`] (https://github.com/mitchellh/vagrant-aws/blob/master/lib/vagrant-aws/version.rb) is `0.6.1` specified...

cheers
schasse

**Comment by rtyler** [comment]
Good catch, it looks like the `release` task didn't push `master` as I had expected it to.
