### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by jamescarr** [mitchellh/vagrant-aws#446]
I'm beginning to think this project has simply died  out. Does otto support (or plan to support) the functionality that used to be supported here?

**Comment by damiandennis** [comment]
how is it dead? A commit was just made in January??

**Comment by cornfeedhobo** [comment]
I am probably opening myself up to ridicule, but I second this question.

https://github.com/mitchellh/vagrant-aws/pull/248
https://github.com/mitchellh/vagrant-aws/pull/358
https://github.com/mitchellh/vagrant-aws/issues/392

These are basic examples of stuff that is important, but not being addressed.

As it is, running the newest Vagrant and vagrant-aws (fresh installs of both), my vagrant loses track of the running instance after it is finished running `up`. :-(

**Comment by znmeb** [comment]
192 open issues? Ouch!

**Comment by EntilZha** [comment]
It would be great to get an update from @mitchellh about the status of the project. I would like to emphasize, its fine if there is not enough time to work on it, but would be good to know that there won't be additional fixes/etc

**Comment by WyseNynja** [comment]
I guess this being closed means it is dying
