### ISSUE TITLE
The security group 'sg-xyz' does not exist (Fog::Compute::AWS::NotFound)

### ISSUE THREAD

**Issue by kenorb** [mitchellh/vagrant-aws#468]
I'm confused with `aws.security_groups`, when I set the group security name as below:

    aws.security_groups = [ "Vagrant" ]

I've got this error:

> InvalidParameterCombination => VPC security groups may not be used for a non-VPC launch

So I've changed my security_group to the ID, since I'm using VPC, like:

    aws.security_groups = [ "sg-011e817a" ]

But I've got another error:

```
==> mt-aws: Please check your security groups settings.
~/.vagrant.d/gems/gems/excon-0.49.0/lib/excon/middlewares/expects.rb:6:in `response_call': The security group 'sg-011e817a' does not exist (Fog::Compute::AWS::NotFound)
	from ~/.vagrant.d/gems/gems/excon-0.49.0/lib/excon/middlewares/response_parser.rb:8:in `response_call'
	from ~/.vagrant.d/gems/gems/excon-0.49.0/lib/excon/connection.rb:389:in `response'
```

Running with debug didn't help much to identify what's the problem.

My group ID exists as shown below:

<img width="1094" alt="screen shot 2016-06-12 at 20 20 11" src="https://cloud.githubusercontent.com/assets/266306/15993357/2347faf6-30db-11e6-898f-4bf62217e9ce.png">

What is the problem here?

--
- Vagrant 1.8.1
- vagrant-aws (0.7.0)
- OS X 10.11.2, VM: Ubuntu
- possibly related: #240

**Comment by egh** [comment]
Security groups are region specific. Is that your issue?

**Comment by kenorb** [comment]
[Most likely](http://stackoverflow.com/a/11886486/55075), thanks, I can't retest that now, since I'm using now default security group. I'll re-test in another time.
