### ISSUE TITLE
Can we get a new release cut that includes the improvements in handling credentials?

### ISSUE THREAD

**Issue by dmcguire81** [mitchellh/vagrant-aws#475]
Specifically, this part of the README is out of date with the latest published version of the Gem (0.7.0):

> Note: if you don't configure aws.access_key_id or aws_secret_access_key it will attempt to read credentials from environment variables first and then from $HOME/.aws/.

In the current published version, aws_profile is not recognized, and the credentials are not read from the environment variables.

**Comment by kenorb** [comment]
Ref: #441, #470, #151

**Comment by rtyler** [comment]
I'm tinkering this weekend with some recent changes. The problem with issues like this, and I don't mean to pick on you specifically @dmcguire81, is they kill any motivation I might have to work on a project. It makes it feel more like an obligation, than something fun.

I think it's generally better to ask "What can I do to help?" than "When will you do X?" (unless you're actually paying somebody for something of course)

**Comment by dmcguire81** [comment]
@rtyler @kenorb Thanks for the quick turn-around time on this request! It helped me immensely with an issue that was a *major* inconvenience (specifically, having to build and host my own patch-version artifact for my team), so I hope that helps fill in some context.

Here were my assumptions when making this request:

- It's trivial to implement (otherwise, I would have issued a PR, as is consistent with my [Github history](https://github.com/pulls?q=is%3Apr+author%3Admcguire81+is%3Aclosed))
- Only the project maintainer has the permissions to cut a release

Just so I'm abreast of proper etiquette for next time, which of those assumptions is incorrect, specifically?
