### ISSUE TITLE
Vagrant up hangs indefinitely

### ISSUE THREAD

**Issue by chrisspen** [mitchellh/vagrant-aws#502]
Running your `VAGRANT_LOG=debug vagrant up --provider aws` seems to create the instance correctly, but it just hangs and never returns. If I terminate it, then it tries to shutdown and terminate the instance, so I can't actually use it. Am I missing something?

**Comment by gianarb** [comment]
Can you post the stdout? In the end you have or not an instance in aws? I am using this plugin every day and it's working. Where is it pending? 

Thanks!

**Comment by chrisspen** [comment]
Nevermind. I was able to get it working.
