### ISSUE TITLE
Message: Gem::Requirement::BadRequirementError: Illformed requirement [">= "]

### ISSUE THREAD

**Issue by haynescw** [mitchellh/vagrant-aws#506]
The moment I installed the vagrant-aws plugin and tried to use 

DRUPALVM_ENV=prod vagrant up --provider=aws

I recieved the above error.

Currently using Vagrant 1.9.2 and the most recent version of the vagrant aws plugin.

Can anyone help?

**Comment by derekderaps** [comment]
@haynescw, did you figure out what was up? I'm seeing the same.
