### ISSUE TITLE
Can't install vagrant-aws because xmlrpc requires Ruby version >= 2.3

### ISSUE THREAD

**Issue by defn** [mitchellh/vagrant-aws#510]
I'm using Vagrant 1.9.4 to install vagrant-aws, which failed to install today with this error:

`xmlrpc requires Ruby version >= 2.3`

I tracked this down to one of the vagrant-aws dependencies: fog-core, which released 1.44.0 today and pulls in xmlrpc.

To workaround, I installed fog-core first with the last compatible gem:

`vagrant plugin install --plugin-version 1.43 fog-core`

Then `vagrant plugin install vagrant-aws` installs successfully.

**Comment by ColinHebert** [comment]
Currently tracked on the fog side: fog/fog-core#206

**Comment by xbeta** [comment]
+1 I have the same issue.

**Comment by dtilchin** [comment]
Root issue resolved in fog-core 1.44.1: https://github.com/fog/fog-core/issues/206

**Comment by defn** [comment]
Plain `vagrant plugin install vagrant-aws` works for me now with the `fog-core 1.44.1` published to rubygems.

**Comment by bethesque** [comment]
I'm getting this error when running `vagrant plugin install vagrant-aws` with vagrant 1.8.4. I'm trying to work out what has changed "recently", because the code itself has not been modified for ages, but started failing around the 29th June.
