### ISSUE TITLE
Authentication is required for http://gems.hashicorp.com/.

### ISSUE THREAD

**Issue by hubeiyichangzy** [mitchellh/vagrant-aws#515]
When I tried to install vagrant-aws. It reported and authentication error. I can open http://gems.hashicorp.com/ on my browser. And did not found sign up link. So is some special configuration need to be set before running vagrant plugin install? Thanks for the help.

$ vagrant plugin install vagrant-aws

> Installing the 'vagrant-aws' plugin. This can take a few minutes...
> Bundler, the underlying system Vagrant uses to install plugins,
> reported an error. The error is shown below. These errors are usually
> caused by misconfigured plugin installations or transient network
> issues. The error from Bundler is:
> 
> Authentication is required for http://gems.hashicorp.com/.
> Please supply credentials for this source. You can do this by running:
>  bundle config http://gems.hashicorp.com/ username:password

$ vagrant -v

> Vagrant
> 1.7.2

**Comment by jamiejackson** [comment]
A colleague of mine started getting this issue, too.

**Comment by ankitgupta07** [comment]
I am on version 1.9.5 and I get the same issue with vagrant-winrm. Any solution to this yet?

**Comment by jfbibeau** [comment]
Had a colleague of mine getting this issue - he was running 1.7.5, upgraded to our supported devenv release of 1.8.3 and problem went away.
