### ISSUE TITLE
uninitialized constant VagrantPlugins::AWS::Action::DestroyConfirm

### ISSUE THREAD

**Issue by artursmet** [mitchellh/vagrant-aws#59]
Hi,
I've found a bug in recent version of vagrant-aws (0.3.0-dev, latest pull from master branch).

Instance destroy fails. Here is the stacktrace:

/home/ubuntu/.vagrant.d/gems/gems/vagrant-aws-0.3.0.dev/lib/vagrant-aws/action.rb:14:in `block in action_destroy': uninitialized constant VagrantPlugins::AWS::Action::DestroyConfirm (NameError)
    from /home/ubuntu/.vagrant.d/gems/gems/vagrant-aws-0.3.0.dev/lib/vagrant-aws/action.rb:13:in`tap'
    from /home/ubuntu/.vagrant.d/gems/gems/vagrant-aws-0.3.0.dev/lib/vagrant-aws/action.rb:13:in `action_destroy'
    from /home/ubuntu/.vagrant.d/gems/gems/vagrant-aws-0.3.0.dev/lib/vagrant-aws/provider.rb:16:in`action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.1/lib/vagrant/machine.rb:130:in `action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.1/plugins/commands/destroy/command.rb:23:in`block in execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.1/lib/vagrant/plugin/v2/command.rb:182:in `block in with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.1/lib/vagrant/plugin/v2/command.rb:180:in`each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.1/lib/vagrant/plugin/v2/command.rb:180:in `with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.1/plugins/commands/destroy/command.rb:22:in`execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.1/lib/vagrant/cli.rb:46:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.1/lib/vagrant/environment.rb:460:in`cli'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.2.1/bin/vagrant:84:in `<top (required)>'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in`load'
    from /opt/vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'

I don't have patch for this, because I don't know ruby.

**Comment by annie2010** [comment]
Hey, 

i found a bug in vagrant-aws-0.6.0 with Vagrant 1.4.3

Details: 

1) $vagrant up --provider=aws

Bringing machine 'default' up with 'aws' provider...
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An unexpected error ocurred when executing the action on the
'default' machine. Please report this as a bug:

uninitialized constant VagrantPlugins::AWS::Action::HandleBox

/home/ubuntu/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action.rb:144:in `block in action_up'
/home/ubuntu/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action.rb:143:in `tap'
/home/ubuntu/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action.rb:143:in `action_up'
/home/ubuntu/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/provider.rb:16:in `action'
/usr/lib/ruby/vendor_ruby/vagrant/machine.rb:130:in `action'
/usr/lib/ruby/vendor_ruby/vagrant/batch_action.rb:63:in `block (2 levels) in run'

2) $vagrant -v
Vagrant 1.4.3

**Comment by mattvonrocketstein** [comment]
I have the same problem with the same versions

**Comment by mcorsen** [comment]
I also have the same problem with the same versions.

**Comment by supadid** [comment]
Same problem, same versions.

**Comment by sgarbesi** [comment]
Getting this after upgrading Ruby from 1.9 to 2.1.1

**Comment by miguelaustro** [comment]
Same here

**Comment by AlaaAttya** [comment]
same here 

An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An unexpected error ocurred when executing the action on the
'default' machine. Please report this as a bug:

uninitialized constant VagrantPlugins::AWS::Action::HandleBox

/home/alaa/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action.rb:144:in `block in action_up'
/home/alaa/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action.rb:143:in `tap'
/home/alaa/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action.rb:143:in `action_up'
/home/alaa/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/provider.rb:16:in `action'
/usr/lib/ruby/vendor_ruby/vagrant/machine.rb:130:in `action'
/usr/lib/ruby/vendor_ruby/vagrant/batch_action.rb:63:in `block (2 levels) in run'

vagrant -v
Vagrant 1.4.3
